class NotFound(Exception):
    pass

class AuthFailure(Exception):
    pass
